login_url: 'https://cloud.joinf.com/login?service=https%3A%2F%2Ftrade.joinf.com%2Frapi%2F%3Fredirect_uri=https%253A%252F%252Ftrade.joinf.com%252Ftms%252Fcustomer%252Fcustomers'
username: 'lcq_ui_yw7'
password: '123456'